### ISSUE TITLE
Update golang to 1.10

### ISSUE THREAD

**Issue by utdrmac** [shamaton/docker-golang-centos6#1]
1.10 is latest stable

**Comment by shamaton** [comment]
@utdrmac 
I updated latest image to go version 1.10.4.
Please see below.
https://cloud.docker.com/swarm/shamaton/repository/docker/shamaton/golang-centos6/general

**Comment by utdrmac** [comment]
Sweet. However, that URL requires signup/login. I think you meant to share this public URL: https://hub.docker.com/r/shamaton/golang-centos6/

**Comment by shamaton** [comment]
Oh, sorry!
Its correct.
